### ISSUE TITLE
No pkts and bytes

### ISSUE THREAD

**Issue by tuttimann** [timfprogs/ipfblocklist#2]
Is it normal that no numbers are shown for pkts and bytes for the blocklists that I have activated?
On the first day I installed this addon some numbers were shown but after 0am no numbers did appear.

**Comment by timfprogs** [comment]
You should get the numbers shown.  They will be reset if you system restarts, but they should soon start counting up again.

Can you check:

- `fcrontab -l` shows a line near the end calling `/usr/local/bin/blocklist.pl`
- `/etc/rc.d/rcsysinit.d/S86blocklist` is a symlink to `/etc/rc.d/init.d/blocklist`
- The Firewall > iptables WUI shows targets for each of the blocklists you've got selected.
